/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

import java.awt.Color;

/**
 *
 * @author Yaco
 */
public class CalculatorUI extends javax.swing.JFrame {
    
    int xMouse, yMouse;
    Color bgColor;
    String num1 ="";
    String num2 ="";
    String operation = "";
    
    
    private void setOperationDisplay(String number){
        

        operationDisplay.setText(operationDisplay.getText() + number);
        
    }
    
    private void addMemory(String number){
        
        
        
        if(operation == ""){
            num1 += number;
        }
        else{
            if((operation =="sum" || operation =="sub" || operation =="mul" || operation =="div"))
            num2 += number;

        }
        System.out.println("num1: " + num1+ " " + "num2: " + num2);
    }
    
    
    
    
    public CalculatorUI() {
        initComponents();
        setResizable(false);
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        buttons = new javax.swing.JPanel();
        num8Btn = new javax.swing.JButton();
        num7Btn = new javax.swing.JButton();
        divisionBtn = new javax.swing.JButton();
        num9Btn = new javax.swing.JButton();
        multiplicationBtn = new javax.swing.JButton();
        num6Btn = new javax.swing.JButton();
        num5Btn = new javax.swing.JButton();
        num4Btn = new javax.swing.JButton();
        subtractionBtn = new javax.swing.JButton();
        num3Btn = new javax.swing.JButton();
        sumBtn = new javax.swing.JButton();
        equalBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        num0Btn = new javax.swing.JButton();
        num2Btn = new javax.swing.JButton();
        num1Btn = new javax.swing.JButton();
        display = new javax.swing.JPanel();
        operationDisplay = new javax.swing.JTextField();
        resultDisplay = new javax.swing.JTextField();
        topBarPanel = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(0, 102, 255));

        buttons.setBackground(new java.awt.Color(0, 102, 255));

        num8Btn.setBackground(new java.awt.Color(255, 51, 51));
        num8Btn.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        num8Btn.setForeground(new java.awt.Color(255, 255, 255));
        num8Btn.setText("8");
        num8Btn.setBorder(null);
        num8Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        num8Btn.setFocusable(false);
        num8Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num8BtnMouseClicked(evt);
            }
        });
        num8Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8BtnActionPerformed(evt);
            }
        });

        num7Btn.setBackground(new java.awt.Color(255, 51, 51));
        num7Btn.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        num7Btn.setForeground(new java.awt.Color(255, 255, 255));
        num7Btn.setText("7");
        num7Btn.setBorder(null);
        num7Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        num7Btn.setFocusable(false);
        num7Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num7BtnMouseClicked(evt);
            }
        });

        divisionBtn.setBackground(new java.awt.Color(255, 102, 51));
        divisionBtn.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        divisionBtn.setForeground(new java.awt.Color(255, 255, 255));
        divisionBtn.setText("/");
        divisionBtn.setBorder(null);
        divisionBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        divisionBtn.setFocusable(false);
        divisionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divisionBtnMouseClicked(evt);
            }
        });

        num9Btn.setBackground(new java.awt.Color(255, 51, 51));
        num9Btn.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        num9Btn.setForeground(new java.awt.Color(255, 255, 255));
        num9Btn.setText("9");
        num9Btn.setBorder(null);
        num9Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        num9Btn.setFocusable(false);
        num9Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num9BtnMouseClicked(evt);
            }
        });

        multiplicationBtn.setBackground(new java.awt.Color(255, 102, 51));
        multiplicationBtn.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        multiplicationBtn.setForeground(new java.awt.Color(255, 255, 255));
        multiplicationBtn.setText("x");
        multiplicationBtn.setBorder(null);
        multiplicationBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        multiplicationBtn.setFocusable(false);
        multiplicationBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplicationBtnMouseClicked(evt);
            }
        });

        num6Btn.setBackground(new java.awt.Color(255, 51, 51));
        num6Btn.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        num6Btn.setForeground(new java.awt.Color(255, 255, 255));
        num6Btn.setText("6");
        num6Btn.setBorder(null);
        num6Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        num6Btn.setFocusable(false);
        num6Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num6BtnMouseClicked(evt);
            }
        });

        num5Btn.setBackground(new java.awt.Color(255, 51, 51));
        num5Btn.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        num5Btn.setForeground(new java.awt.Color(255, 255, 255));
        num5Btn.setText("5");
        num5Btn.setBorder(null);
        num5Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        num5Btn.setFocusable(false);
        num5Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num5BtnMouseClicked(evt);
            }
        });

        num4Btn.setBackground(new java.awt.Color(255, 51, 51));
        num4Btn.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        num4Btn.setForeground(new java.awt.Color(255, 255, 255));
        num4Btn.setText("4");
        num4Btn.setBorder(null);
        num4Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        num4Btn.setFocusable(false);
        num4Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num4BtnMouseClicked(evt);
            }
        });

        subtractionBtn.setBackground(new java.awt.Color(255, 102, 51));
        subtractionBtn.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        subtractionBtn.setForeground(new java.awt.Color(255, 255, 255));
        subtractionBtn.setText("-");
        subtractionBtn.setBorder(null);
        subtractionBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subtractionBtn.setFocusable(false);
        subtractionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subtractionBtnMouseClicked(evt);
            }
        });

        num3Btn.setBackground(new java.awt.Color(255, 51, 51));
        num3Btn.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        num3Btn.setForeground(new java.awt.Color(255, 255, 255));
        num3Btn.setText("3");
        num3Btn.setBorder(null);
        num3Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        num3Btn.setFocusable(false);
        num3Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num3BtnMouseClicked(evt);
            }
        });

        sumBtn.setBackground(new java.awt.Color(255, 102, 51));
        sumBtn.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        sumBtn.setForeground(new java.awt.Color(255, 255, 255));
        sumBtn.setText("+");
        sumBtn.setBorder(null);
        sumBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sumBtn.setFocusable(false);
        sumBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumBtnMouseClicked(evt);
            }
        });

        equalBtn.setBackground(new java.awt.Color(255, 51, 51));
        equalBtn.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        equalBtn.setForeground(new java.awt.Color(255, 255, 255));
        equalBtn.setText("=");
        equalBtn.setBorder(null);
        equalBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        equalBtn.setFocusable(false);
        equalBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equalBtnMouseClicked(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(255, 51, 51));
        clearBtn.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(255, 255, 255));
        clearBtn.setText("C");
        clearBtn.setBorder(null);
        clearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearBtn.setFocusable(false);
        clearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearBtnMouseClicked(evt);
            }
        });

        num0Btn.setBackground(new java.awt.Color(255, 51, 51));
        num0Btn.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        num0Btn.setForeground(new java.awt.Color(255, 255, 255));
        num0Btn.setText("0");
        num0Btn.setBorder(null);
        num0Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        num0Btn.setFocusable(false);
        num0Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num0BtnMouseClicked(evt);
            }
        });

        num2Btn.setBackground(new java.awt.Color(255, 51, 51));
        num2Btn.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        num2Btn.setForeground(new java.awt.Color(255, 255, 255));
        num2Btn.setText("2");
        num2Btn.setBorder(null);
        num2Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        num2Btn.setFocusable(false);
        num2Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num2BtnMouseClicked(evt);
            }
        });

        num1Btn.setBackground(new java.awt.Color(255, 51, 51));
        num1Btn.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        num1Btn.setForeground(new java.awt.Color(255, 255, 255));
        num1Btn.setText("1");
        num1Btn.setBorder(null);
        num1Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        num1Btn.setFocusable(false);
        num1Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num1BtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout buttonsLayout = new javax.swing.GroupLayout(buttons);
        buttons.setLayout(buttonsLayout);
        buttonsLayout.setHorizontalGroup(
            buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonsLayout.createSequentialGroup()
                        .addComponent(num7Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num8Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num9Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(divisionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonsLayout.createSequentialGroup()
                        .addComponent(num4Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num5Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num6Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multiplicationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonsLayout.createSequentialGroup()
                        .addComponent(num1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num3Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subtractionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonsLayout.createSequentialGroup()
                        .addComponent(num0Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sumBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonsLayout.setVerticalGroup(
            buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num7Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num8Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num9Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divisionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num4Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num5Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num6Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplicationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num3Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtractionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num0Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sumBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        display.setBackground(new java.awt.Color(0, 102, 255));

        operationDisplay.setEditable(false);
        operationDisplay.setBackground(new java.awt.Color(255, 255, 255));
        operationDisplay.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        operationDisplay.setForeground(new java.awt.Color(0, 0, 0));
        operationDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        operationDisplay.setBorder(null);
        operationDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationDisplayActionPerformed(evt);
            }
        });

        resultDisplay.setEditable(false);
        resultDisplay.setBackground(new java.awt.Color(255, 255, 255));
        resultDisplay.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        resultDisplay.setForeground(new java.awt.Color(0, 0, 0));
        resultDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        resultDisplay.setBorder(null);

        topBarPanel.setBackground(new java.awt.Color(0, 102, 255));
        topBarPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topBarPanelMouseDragged(evt);
            }
        });
        topBarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                topBarPanelMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topBarPanelMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(0, 102, 255));
        exitBtn.setPreferredSize(new java.awt.Dimension(34, 34));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnMouseExited(evt);
            }
        });

        exitLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(0, 0, 0));
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel.setText("x");

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout topBarPanelLayout = new javax.swing.GroupLayout(topBarPanel);
        topBarPanel.setLayout(topBarPanelLayout);
        topBarPanelLayout.setHorizontalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarPanelLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 296, Short.MAX_VALUE))
        );
        topBarPanelLayout.setVerticalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarPanelLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout displayLayout = new javax.swing.GroupLayout(display);
        display.setLayout(displayLayout);
        displayLayout.setHorizontalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(displayLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(operationDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        displayLayout.setVerticalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayLayout.createSequentialGroup()
                .addComponent(topBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(operationDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(displayLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(resultDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void operationDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_operationDisplayActionPerformed

    private void num8BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num8BtnActionPerformed

    private void topBarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBarPanelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_topBarPanelMousePressed

    private void topBarPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBarPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_topBarPanelMouseDragged

    private void topBarPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBarPanelMouseEntered
        
    }//GEN-LAST:event_topBarPanelMouseEntered

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
        bgColor = exitBtn.getBackground();
        exitBtn.setBackground(Color.red);
        exitLabel.setForeground(Color.white);
    }//GEN-LAST:event_exitBtnMouseEntered

    private void exitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseExited
        exitBtn.setBackground(bgColor);
        exitLabel.setForeground(Color.black);
    }//GEN-LAST:event_exitBtnMouseExited

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void num0BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num0BtnMouseClicked
        
        addMemory("0");
        setOperationDisplay("0");
        
    }//GEN-LAST:event_num0BtnMouseClicked

    private void sumBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumBtnMouseClicked
        operation = "sum";
        setOperationDisplay("+");
        
    }//GEN-LAST:event_sumBtnMouseClicked

    private void num1BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num1BtnMouseClicked
       addMemory("1");
        setOperationDisplay("1");
    }//GEN-LAST:event_num1BtnMouseClicked

    private void num2BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num2BtnMouseClicked
        addMemory("2");
        setOperationDisplay("2");
    }//GEN-LAST:event_num2BtnMouseClicked

    private void num3BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num3BtnMouseClicked
        addMemory("3");
        setOperationDisplay("3");
    }//GEN-LAST:event_num3BtnMouseClicked

    private void num4BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num4BtnMouseClicked
        addMemory("4");
        setOperationDisplay("4");
    }//GEN-LAST:event_num4BtnMouseClicked

    private void num5BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num5BtnMouseClicked
        addMemory("5");
        setOperationDisplay("5");
    }//GEN-LAST:event_num5BtnMouseClicked

    private void num6BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num6BtnMouseClicked
        addMemory("6");
        setOperationDisplay("6");
    }//GEN-LAST:event_num6BtnMouseClicked

    private void num7BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num7BtnMouseClicked
        addMemory("7");
        setOperationDisplay("7");
    }//GEN-LAST:event_num7BtnMouseClicked

    private void num8BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num8BtnMouseClicked
        addMemory("8");
        setOperationDisplay("8");
    }//GEN-LAST:event_num8BtnMouseClicked

    private void num9BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num9BtnMouseClicked
        addMemory("9");
        setOperationDisplay("9");
    }//GEN-LAST:event_num9BtnMouseClicked

    private void subtractionBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subtractionBtnMouseClicked
        
        operation = "sub";
        setOperationDisplay("-");
     
    }//GEN-LAST:event_subtractionBtnMouseClicked

    private void multiplicationBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicationBtnMouseClicked
        operation = "mul";
        setOperationDisplay("x");
    }//GEN-LAST:event_multiplicationBtnMouseClicked

    private void divisionBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisionBtnMouseClicked
        operation = "div";
        setOperationDisplay("/");
    }//GEN-LAST:event_divisionBtnMouseClicked

    private void clearBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseClicked
        operation = "";
        num1 = "";
        num2 = "";
        operationDisplay.setText("");
        resultDisplay.setText("");

    }//GEN-LAST:event_clearBtnMouseClicked

    private void equalBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equalBtnMouseClicked
        
        
        int number1 = Integer.valueOf(num1);
        int number2 = Integer.valueOf(num2);
        String result;
        
        
        if(operation =="sum"){
           
            result = String.valueOf((number1 + number2));
            resultDisplay.setText(num1 + " + " + num2 + " = " + result);
            operationDisplay.setText("");
            num1 = result;
            num2 = "";
            
            
        }
        else if(operation =="sub")
        {
            result = String.valueOf((number1 - number2));
            resultDisplay.setText(num1 + " - " + num2 + " = " + result);
            operationDisplay.setText("");
            num1 = result;
            num2 = "";
        }
        else if(operation =="div")
        {
            if(number2 == 0){
                resultDisplay.setText("Math Error");
            }
            else{
                result = String.valueOf((number1 / number2));
                resultDisplay.setText(num1 + " / " + num2 + " = " + result);
                operationDisplay.setText("");
                num1 = result;
                num2 = "";
            }
            
        }
        else if(operation =="mul")
        {
            result = String.valueOf((number1 * number2));
            resultDisplay.setText(num1 + " x " + num2 + " = " + result);
            operationDisplay.setText("");
            num1 = result;
            num2 = "";;
        }
        else{
            resultDisplay.setText("Syntax Error");
            num1 = "";
            num2 = "";
            operation = "";
        }

        
        
    }//GEN-LAST:event_equalBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel buttons;
    private javax.swing.JButton clearBtn;
    private javax.swing.JPanel display;
    private javax.swing.JButton divisionBtn;
    private javax.swing.JButton equalBtn;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JButton multiplicationBtn;
    private javax.swing.JButton num0Btn;
    private javax.swing.JButton num1Btn;
    private javax.swing.JButton num2Btn;
    private javax.swing.JButton num3Btn;
    private javax.swing.JButton num4Btn;
    private javax.swing.JButton num5Btn;
    private javax.swing.JButton num6Btn;
    private javax.swing.JButton num7Btn;
    private javax.swing.JButton num8Btn;
    private javax.swing.JButton num9Btn;
    private javax.swing.JTextField operationDisplay;
    private javax.swing.JTextField resultDisplay;
    private javax.swing.JButton subtractionBtn;
    private javax.swing.JButton sumBtn;
    private javax.swing.JPanel topBarPanel;
    // End of variables declaration//GEN-END:variables
}
